# Generated by Django 5.0.1 on 2024-02-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="company_id",
            new_name="company",
        ),
    ]
