# Generated by Django 5.0.1 on 2024-02-07 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("call", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="call",
            old_name="company_id",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="call",
            old_name="user_id",
            new_name="user",
        ),
    ]
